name: Conventional Commits

on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ubiquity/action-conventional-commits@master
