name: Typecheck

on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run typecheck
        run: yarn tsc --noEmit
